apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mallard
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous false
    password_file /mosquitto/config/passwd
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
