apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mallard-app-secrets
  namespace: mallard
spec:
  hostAPI: http://infisical.infisical.svc.cluster.local/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: mallard
        envSlug: prod
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-universal-auth-credentials
        secretNamespace: mallard
  managedSecretReference:
    secretName: mallard-app-secrets
    secretNamespace: mallard
