apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../server
  - infisical-secret-mallard.yaml
  - universal-auth-secret.yaml
patches:
  - path: patch-server-envfrom.yaml
    target:
      kind: Deployment
      name: mallard-server
