apiVersion: apps/v1
kind: Deployment
metadata:
  name: mallard-server
  namespace: mallard
spec:
  template:
    spec:
      containers:
        - name: mallard-server
          envFrom:
            - configMapRef:
                name: mallard-server-config
            - secretRef:
                name: mallard-server-secrets
            - secretRef:
                name: mallard-app-secrets
